/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerMatchExplanation = IDL.Record({
  'description' : IDL.Text,
  'matchReasons' : IDL.Text,
  'typicalEducation' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'careerTitle' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'isUser' : IDL.Bool,
  'message' : IDL.Text,
});
export const SurveyScore = IDL.Nat8;
export const SurveyResult = IDL.Record({
  'socialProblemSolving' : SurveyScore,
  'careerSatisfaction' : SurveyScore,
  'itSkills' : SurveyScore,
  'requirementsClarity' : SurveyScore,
  'mathInterest' : IDL.Nat8,
  'mathSkills' : SurveyScore,
  'selfReflection' : SurveyScore,
});
export const SurveyType = IDL.Variant({
  'socialProblemSolving' : IDL.Null,
  'careerSurveyTotalScore' : IDL.Null,
  'careerSatisfaction' : IDL.Null,
  'careerRecommendationScore' : IDL.Null,
  'itSkills' : IDL.Null,
  'requirementsClarity' : IDL.Null,
  'mathInterest' : IDL.Null,
  'mathSkills' : IDL.Null,
  'personalInterest' : IDL.Null,
  'selfReflection' : IDL.Null,
});

export const idlService = IDL.Service({
  'checkRequirements' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Opt(CareerMatchExplanation)],
      [],
    ),
  'clearCareerContent' : IDL.Func([], [], []),
  'getCareerMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getCareerRecommendations' : IDL.Func(
      [SurveyResult],
      [IDL.Opt(IDL.Vec(CareerMatchExplanation))],
      [],
    ),
  'getCompletionStatus' : IDL.Func(
      [IDL.Record({ 'conversationId' : IDL.Text, 'surveyType' : SurveyType })],
      [IDL.Bool],
      [],
    ),
  'getTotalQuestionCount' : IDL.Func([], [IDL.Nat], []),
  'handleCareerRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'startCareerChat' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerMatchExplanation = IDL.Record({
    'description' : IDL.Text,
    'matchReasons' : IDL.Text,
    'typicalEducation' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'careerTitle' : IDL.Text,
  });
  const ChatMessage = IDL.Record({ 'isUser' : IDL.Bool, 'message' : IDL.Text });
  const SurveyScore = IDL.Nat8;
  const SurveyResult = IDL.Record({
    'socialProblemSolving' : SurveyScore,
    'careerSatisfaction' : SurveyScore,
    'itSkills' : SurveyScore,
    'requirementsClarity' : SurveyScore,
    'mathInterest' : IDL.Nat8,
    'mathSkills' : SurveyScore,
    'selfReflection' : SurveyScore,
  });
  const SurveyType = IDL.Variant({
    'socialProblemSolving' : IDL.Null,
    'careerSurveyTotalScore' : IDL.Null,
    'careerSatisfaction' : IDL.Null,
    'careerRecommendationScore' : IDL.Null,
    'itSkills' : IDL.Null,
    'requirementsClarity' : IDL.Null,
    'mathInterest' : IDL.Null,
    'mathSkills' : IDL.Null,
    'personalInterest' : IDL.Null,
    'selfReflection' : IDL.Null,
  });
  
  return IDL.Service({
    'checkRequirements' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Opt(CareerMatchExplanation)],
        [],
      ),
    'clearCareerContent' : IDL.Func([], [], []),
    'getCareerMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCareerRecommendations' : IDL.Func(
        [SurveyResult],
        [IDL.Opt(IDL.Vec(CareerMatchExplanation))],
        [],
      ),
    'getCompletionStatus' : IDL.Func(
        [
          IDL.Record({
            'conversationId' : IDL.Text,
            'surveyType' : SurveyType,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'getTotalQuestionCount' : IDL.Func([], [IDL.Nat], []),
    'handleCareerRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'startCareerChat' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };