/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerMatchExplanation {
  'description' : string,
  'matchReasons' : string,
  'typicalEducation' : string,
  'requiredSkills' : Array<string>,
  'careerTitle' : string,
}
export interface ChatMessage { 'isUser' : boolean, 'message' : string }
export interface SurveyResult {
  'socialProblemSolving' : SurveyScore,
  'careerSatisfaction' : SurveyScore,
  'itSkills' : SurveyScore,
  'requirementsClarity' : SurveyScore,
  'mathInterest' : number,
  'mathSkills' : SurveyScore,
  'selfReflection' : SurveyScore,
}
export type SurveyScore = number;
export type SurveyType = { 'socialProblemSolving' : null } |
  { 'careerSurveyTotalScore' : null } |
  { 'careerSatisfaction' : null } |
  { 'careerRecommendationScore' : null } |
  { 'itSkills' : null } |
  { 'requirementsClarity' : null } |
  { 'mathInterest' : null } |
  { 'mathSkills' : null } |
  { 'personalInterest' : null } |
  { 'selfReflection' : null };
export interface _SERVICE {
  'checkRequirements' : ActorMethod<
    [[] | [bigint], [] | [string]],
    [] | [CareerMatchExplanation]
  >,
  'clearCareerContent' : ActorMethod<[], undefined>,
  'getCareerMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getCareerRecommendations' : ActorMethod<
    [SurveyResult],
    [] | [Array<CareerMatchExplanation>]
  >,
  'getCompletionStatus' : ActorMethod<
    [{ 'conversationId' : string, 'surveyType' : SurveyType }],
    boolean
  >,
  'getTotalQuestionCount' : ActorMethod<[], bigint>,
  'handleCareerRequest' : ActorMethod<[string, string], string>,
  'startCareerChat' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];